server:
  port: 9090
spring:
#  datasource:
#    url: jdbc:mysql://192.168.2.10:3306/test
#    type: com.alibaba.druid.pool.DruidDataSource
#    username: mstest
#    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    database: 0
    host: 192.168.2.10
    port: 6379
    password: null
    jedis:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 0
    timeout: 5000
  application:
    name: spring-jpa-mq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: taotao
    password: taotao
    publisher-confirms: true
    virtual-host: /taotao